// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akbfexwiejfddvjmeofn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrYmZleHdpZWpmZGR2am1lb2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MTYxNzgsImV4cCI6MjA1MjE5MjE3OH0.VOuc3tDgvGrhh76dS2_7gHV3TS6S7Nm8RlJPu5TPEIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);